export interface FuelRecord {
  id: number;
  sysServiceId?: string;
  alertBankId?: number;
  ambulanceNumber?: string;
  vehicle?: string;
  fuelStatus?: string;
  currentReading?: number;
  quantityReading?: number;
  appQuantityReading?: number;
  fuelDifference: number;
  pumpLocation?: string;
  totalAmount?: number;
  otp?: string;
  invoice?: string;
  auditStatus?: 'Audit' | 'OK';
  timestamp?: string;
  previousReading?: number;
  efficiency?: string;
  fuelType?: string;
  driverName?: string;
  dateTime?: string;
  rawTime?: string;
  softwareReadingTotalAmount?: string;
  vehicleno?: string;
  requestedFuel?: string;
  location?: string;
  fuelDate?: string;
  liveFuel?: number | null;
  gpsTime?: string | null;
  amount?: number;
  invoiceFileUrl?: string;
  status?: string;
  statusText?: string;
  created_at?: string;
}
